Release 0.5.0
max-underthesun/react-blog-webpack pull request #2
Opened 2017-02-10 06:43 UTC by max-underthesun

2017-02-10 07:24 UTC, index01d requested changes
чтобы не было путей About/About, можно сделать About/index.js

2017-02-10 07:24 UTC, index01d commented on index.html
> +  <body style="background-color: black;">
почему бы не сделать это в стилевом файле?

2017-02-10 07:24 UTC, index01d commented on src/components/containers/About/AboutContainer.js
> +      'http://localhost:3001/about',
адрес до сервера лучше вынести в константы

2017-02-10 07:24 UTC, index01d commented on src/components/containers/Post/PostContainer.js
> +    const id = this.props.params.id;
или `const { id } = this.props.params`

2017-02-10 07:24 UTC, index01d commented on src/components/shared/widgets/BlogItem.js
> +const blogItemStyle = {
почему бы не вынести это в стилевой файл?

2017-02-10 07:24 UTC, index01d commented on src/routes/Blog.js
> +  path: '/about',
лучше также сделать функцией-хелпером, т.к. путь может меняться

2017-02-10 07:24 UTC, index01d commented on src/components/shared/widgets/BlogItem.js
> +  if (like != undefined) {
интересный вариант условного рендеринга, лучше просто написать
```
React.createElement(MetaData, meta),
React.createElement(Image, image),
React.createElement(TextBox, text),
like && React.createElement(Like, { meta, id, like })
```

Like при этом сделать блоком, тогда не понадобится br.

2017-02-12 09:57 UTC, max-underthesun commented on src/routes/Blog.js
> +  path: '/about',
вынес в хелпер

2017-02-12 09:59 UTC, max-underthesun commented on src/components/containers/Post/PostContainer.js
> +    const id = this.props.params.id;
сделал

2017-02-12 10:16 UTC, max-underthesun commented on src/components/containers/About/AboutContainer.js
> +      'http://localhost:3001/about',
вынес в константы

2017-02-12 11:00 UTC, max-underthesun commented on src/components/shared/widgets/BlogItem.js
> +  if (like != undefined) {
да, так конечно же гораздо элегантней, чем мои костыли :)
переделал

2017-02-12 11:28 UTC, max-underthesun commented on index.html
> +  <body style="background-color: black;">
ага... так лучше

2017-02-12 14:04 UTC, max-underthesun commented on src/components/shared/widgets/BlogItem.js
> +const blogItemStyle = {
вынес

2017-02-13 07:53 UTC, index01d requested changes

2017-02-13 07:53 UTC, index01d commented on src/components/views/About/index.js
> +import About from './About';
а почему сразу в index'e не написать?

2017-02-13 12:02 UTC, max-underthesun commented on src/components/views/About/index.js
> +import About from './About';
написал

2017-02-13 12:04 UTC, index01d approved these changes

2017-02-13 12:09 UTC, max-underthesun commented
о спасибо! ))

2017-02-21 04:55 UTC, merged