Release 0.6.0
max-underthesun/react-blog-webpack pull request #3
Opened 2017-04-06 12:06 UTC by max-underthesun

вопросы в коде!

2017-04-06 12:17 UTC, max-underthesun commented on src/components/views/BlogPage/index.js
> +    const itemsPaginated = this.paginate(items);
в данном случае, у меня в памяти создается новый объект и в него копируются все данные из items?
или в объекте будут ссылки на items?

я имею в виду, что хочется понять насколько уместно такое решение для паджинации
или стоит попробовать создать объект с индексами и при переходах по страницам выбирать из items по индексам?

2017-04-06 12:20 UTC, max-underthesun commented on src/components/views/BlogPage/index.js
> +  }
насколько уместен такой подход к паджинации?
можно/нужно сделать лучше/правильней?

2017-04-06 18:41 UTC, max-underthesun commented on src/routes/Blog.js
> +    }
блок `if - else` в `prepareData` кажется мне несколько "лубочным", но другого варианта "не придумалось"

2017-04-07 15:51 UTC, index01d commented on src/components/views/BlogPage/index.js
> +  }
в таком варианте нет ссылки и соответственно страницы не будут проиндексированы поисковиком (или будут проиндексированы сильно позже и фрагментированно)

2017-04-07 15:51 UTC, index01d commented on src/components/views/BlogPage/index.js
> +  }
лучше делать Link

2017-04-07 15:54 UTC, index01d requested changes
Настройки и состояние пейджинации необходимо унести в общее Redux-состояние (например формируемое в reducer'e списка записей под ключ pagination). Управлять ими нужно посредством action'ов, формируя при этом в actionsToProps (втором параметре функции connect) соответствующие коллбэки

2017-04-07 15:54 UTC, index01d commented on src/components/views/BlogPage/index.js
> +  like(id) {
должно быть в контейнере

2017-04-07 15:54 UTC, index01d commented on src/components/views/BlogPage/index.js
> +  paginate(items) {
должно быть в контейнере

2017-04-07 15:55 UTC, index01d commented on src/routes/Blog.js
> +    }
вполне можно так.

2017-04-07 16:59 UTC, index01d commented on src/components/views/BlogPage/index.js
> +    const itemsPaginated = this.paginate(items);
можно сделать выборку из состояния в stateToProps. Так будет наиболее правильно.

2017-04-17 05:54 UTC, max-underthesun commented on src/components/views/BlogPage/index.js
> +    const itemsPaginated = this.paginate(items);
так и сделал
надеюсь я правильно понял идею ))

2017-04-17 05:54 UTC, max-underthesun commented on src/components/views/BlogPage/index.js
> +  like(id) {
унес в контейнер

2017-04-17 05:55 UTC, max-underthesun commented on src/components/views/BlogPage/index.js
> +  paginate(items) {
унес в контейнер

2017-04-17 05:55 UTC, max-underthesun commented on src/routes/Blog.js
> +    }
ок

2017-04-17 06:36 UTC, max-underthesun commented on src/components/views/BlogPage/index.js
> +  }
сделал

2017-04-17 06:41 UTC, max-underthesun commented
что-то у меня в мозгу общая рекомендация по проекту "Настройки и состояние пейджинации необходимо унести в общее Redux-состояние... " и частные рекомендации  "можно сделать выборку из состояния в stateToProps. Так будет наиболее правильно.", "должно быть в контейнере" вступили в небольшое противоречие... 

в итоге:
- паджинация рулится в контейнере
-  в состояние (и в контейнер) унес лайки

кстати вопрос:
насколько "стилистически правильно"  делать отдельный контейнер для столь малого элемента, как Like и помещать его в папку containers?
или оставить connect прямо в компоненте? или лучше контейнер куда-то еще положить?

что-то еще можно/нужно улучшить или пока идем дальше?

2017-04-17 06:58 UTC, index01d commented
не совсем понял в чем противоречие: разверни если не сложно, я тогда смогу пояснить:)

Сделать отдельный контейнер не страшно. Не страшно при этом держать connect прямо в компоненте. Главное в этом деле – единообразие. То есть нужно принять некоторую собственную конвенцию в проекте и везде ей следовать:
* Можно всегда уносить в контейнер
* Можно всегда держать с компонентом
* Можно сделать файловую структуру где вместе с компонентом хранятся его контейнеры, action'ы и reducer'ы (типа `ToDoList/[containers, actions, reducers, components, routes]; Comments/[containers, actions, reducers, components, routes]`)

Все методы имеют кучу минусов и плюсов и нужно уже от собственных предпочтений и специфики проекта отталкиваться.

2017-04-17 08:00 UTC, max-underthesun commented
ну противоречие у меня в том, что рекомендацию "Настройки и состояние пейджинации необходимо унести в общее Redux-состояние... " я понимаю так:
- сделать в сторе ключи `itemsPaginated`, `itemsCurrent`, `pageNumbers`
- добавить экшены, которые бы использовали для вычислений функции из компонента
- в ключи с помощью этих новых экшенов  записать нужные данные
- в компоненте пользоваться этими данными, передавая их из стора с помощью `stateToProps`

а рекомендации "можно сделать выборку из состояния в stateToProps. Так будет наиболее правильно.", "должно быть в контейнере" я понял так:
- в контейнере из стора доставать `items`
- в тот же файл контейнера унести функции для вычислений
- с помощью этих функций из `items` вычислять нужные переменные `itemsPaginated`, `itemsCurrent`, `pageNumbers`
- переменные далее прокидывать компоненту опять же с помощью `stateToProps`

получается, что в первом случае,  `itemsPaginated`, `itemsCurrent`, `pageNumbers` хранятся в сторе,  вычисляются "заранее" по диспатчу соответствующих экшенов, во втором - вычисляются в контейнере

в этом я и увидел противоречие ))

пошел я вторым путем, он показался проще

первый вариант я тоже попробовал, но там кода побольше, плюс столкнулся с тем, что появляется необходимость согласовывать в сторе поля `posts.entries` и `posts.itemsPaginated`, т.к. изменение данных в одном (судя по работе приложения) не ведет к изменениям в другом, т.е. в сторе это похоже уже не ссылка из одного объекта на другой, а новый объект... 
поэтому, либо отказываться от одного из этих полей совсем, либо их синхронизировать как-то, т.е. лишние сложности

по заданию еще есть замечания? 
или переходить к 7-му уроку?

2017-04-17 16:41 UTC, index01d commented
ну просто есть третий вариант:
* Избавиться от itemsPaginated (если я правильно понял то тут копия записей)
* Занести настройки пейджинации под ключ pagination: { current, itemsOnPage }
* В контейнере в соответствии с текущими настройками делать выборку из списка записей

2017-04-17 16:46 UTC, index01d requested changes

2017-04-17 16:46 UTC, index01d commented on src/components/containers/PostsContainer.js
> +function paginate(items) {
От этой функции лучше избавиться. Нам ни к чему заранее разбивать записи на страницы. Мы вполне можем позволить себе сделать выборку необходимых записей для текущей страницы в stateToProps

2017-04-17 16:46 UTC, index01d commented on src/components/containers/PostsContainer.js
> +function paginate(items) {
Оптимизация здесь прямо скажем "грошевая":)

2017-04-18 19:11 UTC, max-underthesun commented
сделал сначала pagination ключом редьюсера posts...
а потом что-то разошелся и унес вообще в отдельный редьюсер... 
а потом подумал "а может не надо было"...

2017-04-20 08:39 UTC, index01d commented
поидее выносить не стоило прямо под отдельный ключ, так как настройки пейджинации могут быть индивидуальными для разных сущностей. Но прув

2017-04-20 08:40 UTC, index01d approved these changes

2017-04-26 07:55 UTC, merged